name: integration-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: false
          start: npm start
          working-directory: /
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: e63a7946-58c1-48bf-9a6b-c0c832a5g137